-- 히든젬 게시판 스키마 (MySQL)
-- 실행: check-db.bat init

CREATE TABLE USERS (
    USER_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME   VARCHAR(50)  NOT NULL,
    PASSWORD   VARCHAR(100) NOT NULL,
    NICKNAME   VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UK_USERS_USERNAME ON USERS (USERNAME);

CREATE TABLE POSTS (
    POST_ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY          VARCHAR(20)  NOT NULL,
    TITLE             VARCHAR(200) NOT NULL,
    CONTENT           TEXT,
    THUMBNAIL_URL     VARCHAR(500),
    SIDO              VARCHAR(50),
    GUNGU             VARCHAR(50),
    GEM_SCORE         DECIMAL(10, 2),
    FOREIGN_VISITORS  BIGINT,
    DOMESTIC_VISITORS BIGINT,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_POSTS_CATEGORY CHECK (CATEGORY IN ('AI', 'DOMESTIC', 'FOREIGN'))
);

CREATE INDEX IX_POSTS_CATEGORY ON POSTS (CATEGORY);
CREATE INDEX IX_POSTS_CREATED ON POSTS (CREATED_AT DESC);
